[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "MYSQLPORT"

[[redirects]]
  from = "/api/*"
  to = "/netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
